# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-19 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
