# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-26 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180826_1604'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='orders_customer',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders_order',
        ),
        migrations.AlterModelTable(
            name='pizza',
            table='orders_pizza',
        ),
    ]
